# Enterprise Configuration - Compliance and comprehensive analysis
# For enterprise environments requiring detailed reporting and compliance

target:
  repo: "https://github.com/organization/repository"

scanning:
  semgrep:
    enabled: true
    path: "semgrep"
    config: "compliance"
    custom_flags: "--config p/cwe-top-25 --config p/owasp-top-10 --config p/security-audit --config p/secrets --config p/supply-chain --timeout 900 --max-target-bytes 5000000"
  trufflehog:
    enabled: true
    path: "trufflehog"
    verify_secrets: true

ai_automation:
  enabled: true
  model: "claude-3-5-sonnet-20241022"
  min_confidence: 0.85  # Conservative confidence for enterprise
  auto_fix: false  # Manual review required
  create_pr: false
  create_issue: true

github:
  auth_method: "app"  # Enterprise GitHub App
  app_id: 123456
  app_key_file: "/etc/github-app/private-key.pem"

performance:
  threads: 5  # Conservative threading for stability
  output_dir: "/var/log/security-scans"
  debug: true  # Enable debug logging for enterprise

agent_validation:
  enabled: true
  confidence_threshold: 0.9  # High confidence for enterprise environments