# Security-Focused Configuration - Prioritizing security vulnerabilities
# Equivalent to security-focused.conf preset

target:
  repo: "https://github.com/owner/repo"  # Replace with your repository

scanning:
  semgrep:
    enabled: true
    path: "semgrep"
    config: "security-focused"
    custom_flags: "--config p/security-audit --config p/owasp-top-10 --config p/secrets --timeout 400"
  trufflehog:
    enabled: true
    path: "trufflehog"
    verify_secrets: true

ai_automation:
  enabled: true
  model: "claude-3-5-sonnet-20241022"
  min_confidence: 0.9  # Higher confidence for security fixes
  auto_fix: true
  create_pr: false  # Manual review recommended for security fixes
  create_issue: true

github:
  auth_method: "token"

performance:
  threads: 8
  output_dir: "./results"
  debug: false

agent_validation:
  enabled: true
  confidence_threshold: 0.8  # Higher threshold for security findings