run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell

  disable:
    - gosec
    - exhaustive
    - funlen
    - lll

linters-settings:
  gofmt:
    simplify: true
  
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
    
    - path: vendor/
      linters:
        - typecheck
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0